repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
        exclude: \.txt$
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-builtin-literals
    -   id: flake8
        args: [--max-line-length=120]

- repo: local
  hooks:
    - id: isort
      name: isort
      stages: [commit]
      language: system
      entry: poetry run isort
      types: [python]

    - id: black
      name: black
      stages: [commit]
      language: system
      entry: poetry run black
      types: [python]

    - id: flake8
      name: flake8
      stages: [commit]
      language: system
      entry: poetry run flake8 --ignore=E225 --max-line-length=119
      types: [python]
