[package]
name = "day-19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "day19"
path = "src/lib.rs"

[dependencies]
aocd = "0.4.0"
itertools = "0.12.0"
